name: test
on: [push, pull_request]

jobs:
  # Runs the tests on combinations of the supported python/os matrix.
  test_code:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8]
      fail-fast: false

    steps:
      - uses: actions/checkout@v1

      - name: Setup conda
        uses: goanpeca/setup-miniconda@v1
        with:
          miniconda-version: 'latest'
          python-version: ${{ matrix.python-version }}
          activate-environment: eqcorrscan-test
          environment-file: .github/test_conda_env.yml
          condarc-file: .github/test_condarc.yml

      - name: MacOS specific setup
        shell: bash -l {0}
        if: matrix.os == 'macos-latest'
          run: |
            conda install clangdev>=4 openmp>=4 libcxx>=4 cctools clang clang_osx-64 compiler-rt libcxx llvm-openmp>=4.0.1
#      - name: Windows specific setup
#        shell: bash -l {0}
#        if: matrix.os == 'windows-latest'
#          run: |
#            cp misc/appveyor/fftw3.h eqcorrscan/utils/src/fftw3.h


      - name: install eqcorrscan
        shell: bash -l {0}
        run: |
          pip install -e .
      - name: print package info
        shell: bash -l {0}
        run: |
          conda info -a
          conda list
      - name: run main test suite
        shell: bash -l {0}
        run: |
          py.test -n 2 -m "not serial and not network and not superslow" --cov-report=xml
      - name: run slow tests
        shell: bash -l {0}
        run: |
          py.test -v -m "slow and not serial and not network" --cov-report=xml --cov-append
      - name: run serial test
        shell: bash -l {0}
        run: |
          export OMP_NUM_THREADS=2
          py.test -m "serial and not network" --cov-report=xml --cov-append
      - name: upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          yml: ./codecov.yml
          fail_ci_if_error: true
# This is a very useful step for debugging, it allows you to ssh into the CI
# machine (https://github.com/marketplace/actions/debugging-with-tmate).
# Make sure to open the log before the job starts else you cant see the tmate
# url. See https://github.com/mxschmitt/action-tmate/issues/1.
# Also, the CI machine will close on a non-zero exit code (annoying). This can
# be overcome by coalescing the null command like so:
# $ some-command-that-can-fail || :
#
#- name: Setup tmate session
#  uses: mxschmitt/action-tmate@v1